# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 630397ee0f0d22c15503ac260e8bac51bed20fd1f51c70d03b9d6673fd966bfc1b48ad04583c74660fa12e082dbf8e30f00de784d0b372d0a90a1bbcf0694e7a

test:
  secret_key_base: d9c08bc72aa99bd4f2c85720f716a23edfb84e3cd00c4117de1748f8c6052831bd1442d5ee74ecc8d08ef887cf7337d43676be45b22c816ae92e494086d83cbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
